# Project information
site_name: Technical-Write Me
# site_url:
site_author: Javier Hern치ndez Fern치ndez
site_description: >-
  My technical writer resume and articles about technical writing-related topics

# Repository
# repo_name: 
# repo_url: 
#edit_uri: 
# Copyright
copyright: Copyright &copy; 2022 Javier Hern치ndez Fern치ndez

# Configuration
theme:
  name: material
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - header.autohide
    - search.suggest
  palette:
    - scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  icon:
    logo: assets/cube.png
  logo: assets/cube.png


# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - fenced_code
  - meta
  - wikilinks
  - md_in_html
  - sane_lists
  - toc:
      # permalink: true
      permalink: '#'
      baselevel: 1
      separator: '_'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Plugins  
# Page tree
nav:
  - Home: index.md
  - Articles:
      - Improving Your Documentation Project:
          - First Steps: improving-documentation-projects/part-1/index.md  
          - Getting Feedback from Your Users: improving-documentation-projects/part-2/index.md  
          - Actioning Our Users' Feedback: improving-documentation-projects/part-3/index.md 
      - Single-Responsibility Principle for Documentation Projects: single-responsibility-principle-tw/index.md
  - About Me: about-me/index.md
